---
# tasks/main.yml

- name: shell | docker login
  shell: >
    docker login
    --username={{ docker_registry_username }}
    --password={{ docker_registry_password }}
    {{ docker_registry_url }}

- name: shell | docker login to aws ecr
  shell: >
    $(aws ecr get-login
    --no-include-email
    --region {{ ecr_region | default('ap-southeast-1') }})
